name: Deploy Vitest coverage to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Run tests and upload coverage artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure pnpm is available
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run vitest (CI) to generate coverage
        run: pnpm run test:ci

      - name: Show coverage files (debug)
        run: ls -la coverage || true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifact
          path: coverage

  deploy:
    name: Deploy coverage to gh-pages branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifact
          path: coverage

      - name: Deploy to gh-pages (safe)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: gh-pages
          # create an explicit commit message including the sha
          commit_message: "ci: update coverage from ${GITHUB_SHA}"
          # keep files from previous builds only if needed; default is replace
          allow_empty_commit: true
